### ISSUE TITLE
Interactive prototyping in Jupyter

### ISSUE THREAD

**Issue by dalupus** [tpietruszka/hyperspace_explorer#1]
Extremely interesting package.  I would love to understand how you use it to do the interactive prototyping.  

https://github.com/tpietruszka/hyperspace_explorer#interactive-prototyping-in-jupyter

**Comment by tpietruszka** [comment]
@dalupus I have marked it as closed, but please do let me know if the example makes sense. 

After working on this alone for a while, sometimes I am not sure what might only make sense to me.

**Comment by dalupus** [comment]
thanks
